### ISSUE TITLE
Failing optimizer tests

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#36]
As seen in [this CI log](https://travis-ci.org/odlgroup/odl/jobs/91662646) the optimizer test occasionally fails.

**Comment by kohr-h** [comment]
Why would that happen? A Python 3 thing? There's no random input...

**Comment by aringh** [comment]
I had some problem with that, but thought I fixed it... I had problems with the CG method. Sometimes it crashed due to `ZeroDivisionError` (or whatever it is called). It occurred in line 147
`alpha = sqnorm_r_old / p.inner(Ap)`
in file https://github.com/odlgroup/odl/blob/master/odl/solvers/iterative/iterative.py (I don't know how you link nicely in git...). My take on it was that if you do to many iterations in CG (more than the dimensions of the space) then you will in the end find p = 0.

**Comment by aringh** [comment]
There is random input: c is random.

**Comment by aringh** [comment]
And when I say fixed above, I mean that I put the number of CG iterations to 3 in the example.

**Comment by kohr-h** [comment]
Okay, so that's where the trouble comes from. In that case I'd say that we don't use randomized input for calculations which are more complex than summing two elements or taking a norm.

**Comment by adler-j** [comment]
Linking on git:

`[in file](https://github.com/odlgroup/odl/blob/master/odl/solvers/iterative/iterative.py)`

becomes

[in file](https://github.com/odlgroup/odl/blob/master/odl/solvers/iterative/iterative.py)

**Comment by aringh** [comment]
The problem should be solved by [this commit](https://github.com/odlgroup/odl/commit/e54bc5bb79a512c0abb20aeb0728be22a4e379c3).

**Comment by kohr-h** [comment]
Great!

**Comment by adler-j** [comment]
I don't quite like this, we did not fix the core issue. Our code should not be throwing zero division errors, instead it should exit gracefully. If we want to close this we should make a new issue for this to be fixed.

**Comment by aringh** [comment]
I was just about to open a new issue on the CG method ;)

**Comment by adler-j** [comment]
Great, link it here then and after that close this!

**Comment by aringh** [comment]
Done!

**Comment by adler-j** [comment]
Oh and a short tip, you can reference commits by writing the first numbers in their hash'es

`e54bc5bb` -> e54bc5bb

Also you forgot to link it here! Someone searching this issue would probably like to know how it was resolved.

#40

**Comment by aringh** [comment]
Ah! You meant that this issue should link to the new issue. Check!

**Comment by adler-j** [comment]
Yeah, but I missed that you linked to this guy from the new issue, that alone should be sufficient, not much gain from linking both ways in general. My mistake :(
